DROP TABLE DONANTE CASCADE CONSTRAINT;
CREATE TABLE DONANTE(
    N_DONANTE NUMBER(10) CONSTRAINT donante_pk PRIMARY KEY,
    IDENTIFICACION VARCHAR2(15) UNIQUE,
    NOMBRE VARCHAR2(25) NOT NULL,
    APELLIDO1 VARCHAR2(25) NOT NULL,
    APELLIDO2 VARCHAR2(25) NOT NULL,
    EMAIL VARCHAR2(50),
    ESTADO VARCHAR2(50),
    TELEFONO NUMBER(11),
    COD_POSTAL NUMBER(25),
    FECHA_NACIMIENTO VARCHAR2(25),
    FOTO BLOB,
    SEXO VARCHAR2(10),
    GRUPO_SANGRE VARCHAR2(10),
    CICLO VARCHAR2(10)
    );

    
DROP TABLE FORMULARIO CASCADE CONSTRAINT;
CREATE TABLE FORMULARIO( 
    
    CODIGO_FORM NUMBER (10) CONSTRAINT Formulario_pk PRIMARY KEY,
    PREGUNTA1 VARCHAR2 (2),
    PREGUNTA2 VARCHAR2 (2), 
    PREGUNTA3 VARCHAR2 (2),
    PREGUNTA4 VARCHAR2 (2), 
    PREGUNTA5 VARCHAR2 (2), 
    PREGUNTA6 VARCHAR2 (2), 
    PREGUNTA7 VARCHAR2 (2), 
    PREGUNTA8 VARCHAR2 (2), 
    PREGUNTA9 VARCHAR2 (2), 
    PREGUNTA10 VARCHAR2 (2),
    PREGUNTA11 VARCHAR2 (2),
    PREGUNTA12 VARCHAR2 (2),
    PREGUNTA13 VARCHAR2 (2),
    PREGUNTA14 VARCHAR2 (2),
    PREGUNTA15 VARCHAR2 (2),
    PREGUNTA16 VARCHAR2 (2),
    PREGUNTA17 VARCHAR2 (2),
    PREGUNTA18 VARCHAR2 (2),
    PREGUNTA19 VARCHAR2 (2),
    PREGUNTA20 VARCHAR2 (2), 
    PREGUNTA21 VARCHAR2 (2), 
    PREGUNTA22 VARCHAR2 (2), 
    PREGUNTA23 VARCHAR2 (2), 
    PREGUNTA24 VARCHAR2 (2), 
    PREGUNTA25 VARCHAR2 (2), 
    PREGUNTA26 VARCHAR2 (2), 
    PREGUNTA27 VARCHAR2 (2), 
    PREGUNTA28 VARCHAR2 (2), 
    PREGUNTA29 VARCHAR2 (2), 
    PREGUNTA30 VARCHAR2 (2), 
    PREGUNTA31 VARCHAR2 (2),
    PREGUNTA32 VARCHAR2 (2),
    PREGUNTA33 VARCHAR2 (2),
    PREGUNTA34 VARCHAR2 (2),
    PREGUNTA35 VARCHAR2 (2),
    FECHA_FORM VARCHAR2(25)    
);

DROP TABLE RELLENA CASCADE CONSTRAINT;

CREATE TABLE RELLENA(
     CODIGO_FORM NUMBER (10) NOT NULL,
     N_DONANTE NUMBER(25),
    FOREIGN KEY(CODIGO_FORM) REFERENCES FORMULARIO ON DELETE CASCADE,
    FOREIGN KEY(N_DONANTE) REFERENCES DONANTE ON DELETE CASCADE,
    CONSTRAINT Rellena_pk PRIMARY KEY(CODIGO_FORM, N_DONANTE)
    );

    DROP TABLE DONACION CASCADE CONSTRAINT;

CREATE TABLE DONACION(

    NUM_DONACION NUMBER(5)  CONSTRAINT donacion_pk PRIMARY KEY,
    FECHA VARCHAR2(25) ,
    TIPO_DONACION VARCHAR2(10),
    PULSO VARCHAR2(10),
    TA_SIST VARCHAR2(10),
    TA_DIAS VARCHAR2(10),
    HB_CAP VARCHAR2(10),
    HB_VEN VARCHAR2(10),
    VOLUMEN NUMBER(10)
    

);

DROP TABLE REALIZA CASCADE CONSTRAINT;

CREATE TABLE REALIZA(
     NUM_DONACION NUMBER(5) NOT NULL,
     N_DONANTE NUMBER(25) NOT NULL,
    FOREIGN KEY(NUM_DONACION ) REFERENCES DONACION ON DELETE CASCADE,
    FOREIGN KEY(N_DONANTE) REFERENCES DONANTE ON DELETE CASCADE,
     CONSTRAINT Realiza_pk PRIMARY KEY(NUM_DONACION , N_DONANTE)
    );
    